export const select_part = [
    { value: '', label: '-- เลือกอะไหล่ --', img: '/icon/car-part.png', className: 'w-6' },
    { value: 'front_bumper', label: 'กันชนหน้า', img: '/car_parts/front-bumper.png', className: 'w-8' },
    { value: 'rear_bumper', label: 'กันชนหลัง', img: '/car_parts/rear-bumper.png', className: 'w-7' },
    { value: 'grille', label: 'กระจังหน้า', img: '/car_parts/grille.png', className: 'w-7' },
    { value: 'mirror', label: 'กระจกมองข้าง', img: '/car_parts/mirror.png', className: 'w-6' },
    { value: 'headlight', label: 'ไฟหน้า', img: '/car_parts/headlight.png', className: 'w-6' },
    { value: 'taillight', label: 'ไฟท้าย', img: '/car_parts/taillight.png', className: 'w-5' },
    { value: 'door', label: 'ประตู', img: '/car_parts/door.png', className: 'w-5' },
]

export const car_model_year = {
    'Camry': [2017, 2018, 2019, 2020, 2021, 2022, 2023],
    'Corolla cross': [2022, 2023],
    'Yaris ativ': [2018, 2019],
    'Yaris sedan': [2019],
    'Yaris hatchback': [2017, 2020],
    'Altis': [2019, 2020, 2021, 2022],
};

export const select_province = [
    { value: "BKK", name_th: "กรุงเทพมหานคร" },
    { value: "KBI", name_th: "กระบี่" },
    { value: "KNR", name_th: "กาญจนบุรี" },
    { value: "KSN", name_th: "กาฬสินธุ์" },
    { value: "KPT", name_th: "กำแพงเพชร" },
    { value: "KKN", name_th: "ขอนแก่น" },
    { value: "CTI", name_th: "จันทบุรี" },
    { value: "CCO", name_th: "ฉะเชิงเทรา" },
    { value: "CBI", name_th: "ชลบุรี" },
    { value: "CNT", name_th: "ชัยนาท" },
    { value: "CPM", name_th: "ชัยภูมิ" },
    { value: "CPN", name_th: "ชุมพร" },
    { value: "CRA", name_th: "เชียงราย" },
    { value: "CMI", name_th: "เชียงใหม่" },
    { value: "TRG", name_th: "ตรัง" },
    { value: "TRT", name_th: "ตราด" },
    { value: "TAK", name_th: "ตาก" },
    { value: "NYK", name_th: "นครนายก" },
    { value: "NPT", name_th: "นครปฐม" },
    { value: "NPM", name_th: "นครพนม" },
    { value: "NMA", name_th: "นครราชสีมา" },
    { value: "NST", name_th: "นครศรีธรรมราช" },
    { value: "NSW", name_th: "นครสวรรค์" },
    { value: "NBI", name_th: "นนทบุรี" },
    { value: "NWT", name_th: "นราธิวาส" },
    { value: "NAN", name_th: "น่าน" },
    { value: "BKN", name_th: "บึงกาฬ" },
    { value: "BRM", name_th: "บุรีรัมย์" },
    { value: "PTE", name_th: "ปทุมธานี" },
    { value: "BTG", name_th: "เบตง" },
    { value: "PKN", name_th: "ประจวบคีรีขันธ์" },
    { value: "PRI", name_th: "ปราจีนบุรี" },
    { value: "PTN", name_th: "ปัตตานี" },
    { value: "AYA", name_th: "พระนครศรีอยุธยา" },
    { value: "PYO", name_th: "พะเยา" },
    { value: "PNA", name_th: "พังงา" },
    { value: "PLG", name_th: "พัทลุง" },
    { value: "PCT", name_th: "พิจิตร" },
    { value: "PLK", name_th: "พิษณุโลก" },
    { value: "PBI", name_th: "เพชรบุรี" },
    { value: "PBN", name_th: "เพชรบูรณ์" },
    { value: "PRE", name_th: "แพร่" },
    { value: "PKT", name_th: "ภูเก็ต" },
    { value: "MSK", name_th: "มหาสารคาม" },
    { value: "MDH", name_th: "มุกดาหาร" },
    { value: "MSN", name_th: "แม่ฮ่องสอน" },
    { value: "YST", name_th: "ยโสธร" },
    { value: "YLA", name_th: "ยะลา" },
    { value: "RET", name_th: "ร้อยเอ็ด" },
    { value: "RNG", name_th: "ระนอง" },
    { value: "RYG", name_th: "ระยอง" },
    { value: "RBR", name_th: "ราชบุรี" },
    { value: "LBR", name_th: "ลพบุรี" },
    { value: "LPG", name_th: "ลำปาง" },
    { value: "LPN", name_th: "ลำพูน" },
    { value: "LOE", name_th: "เลย" },
    { value: "SSK", name_th: "ศรีสะเกษ" },
    { value: "SNK", name_th: "สกลนคร" },
    { value: "SKA", name_th: "สงขลา" },
    { value: "STN", name_th: "สตูล" },
    { value: "SPK", name_th: "สมุทรปราการ" },
    { value: "SKM", name_th: "สมุทรสงคราม" },
    { value: "SKN", name_th: "สมุทรสาคร" },
    { value: "SKW", name_th: "สระแก้ว" },
    { value: "SRI", name_th: "สระบุรี" },
    { value: "SBR", name_th: "สิงห์บุรี" },
    { value: "STI", name_th: "สุโขทัย" },
    { value: "SPB", name_th: "สุพรรณบุรี" },
    { value: "SNI", name_th: "สุราษฎร์ธานี" },
    { value: "SRN", name_th: "สุรินทร์" },
    { value: "NKI", name_th: "หนองคาย" },
    { value: "NBP", name_th: "หนองบัวลำภู" },
    { value: "ATG", name_th: "อ่างทอง" },
    { value: "ACR", name_th: "อำนาจเจริญ" },
    { value: "UDN", name_th: "อุดรธานี" },
    { value: "UTD", name_th: "อุตรดิตถ์" },
    { value: "UTI", name_th: "อุทัยธานี" },
    { value: "UBN", name_th: "อุบลราชธานี" }
];